baseURL = "https://golang.org.ve/"
languageCode = "es-ES"
title = "Golang Venezuela"
theme = "main"

[params]
	author = "Golang Venezuela"
	authorAlt = "Comunidad Golang Venezuela"
	domain = "Golang.org.ve"
	favicon = "/img/favicon.png"
	protocol = "https"
	langCode = "es_ES"
	email = "golang@url.co.ve"

[params.seo]
	fbid = "1738958976390281"
	locale = "es_ES"
	title = "Bienvenido a la Comunidad Golang Venezuela"
	description = "Bienvenidos a la comunidad oficial de desarrolladores Golang en Venezuela. Encuentra recursos, concejos y repositorios Golang libres."
	img = "/img/seo.jpg"
	imgjson = "seo.jpg"
	gverification = "a9546a27e16d42c9955d89ea969c48f7"

[permalinks]
	post = "/:slug/"

[params.social]
	facebook = "GolangVE"
	twitter = "GolangVE"
	telegram = "GolangVE"
	youtube = "GolangVE"
	gitlab = "GolangVE"
	github = "GolangVE"

[params.ui]
    primary = "#00bcd4 cyan"
    primary_dark = "#0097a7 cyan darken-2"
    primary_light = "#b2ebf2 cyan lighten-4"
    accent = "#ff5252 red accent-2"
    primary_text = "#212121 grey darken-4"
    secondary_text = "#424242 grey darken-3"
    divider = "#bdbdbd grey lighten-1"
