baseurl = "http://golang.org.ve"
languageCode = "es-es"
title = "Golang Venezuela"
theme = "golangve"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Golang Venezuela"
	description = "Somos la comunidad oficial de desarrolladores Golang en Venezuela"
	copyright = "Golang Venezuela"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/GolangVE/SitioWeb"

	version = "0.2"
	logo = "/images/logo.png"
	favicon = "/images/icono.png"
	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "red"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "GolangVE"
	github  = "GolangVE"
	email   = "golang@url.co.ve"


[[menu.main]]
	name   = "La Comunidad"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "Herramientas"
	url    = "herramientas/"
	weight = 20

[[menu.main]]
	name   = "Repositorios"
	url    = "repositorios/"
	weight = 30

[[menu.main]]
	name   = "Certificaciones"
	url    = "certificaciones/"
	weight = 40

[[menu.main]]
	name   = "Licencias"
	url    = "licencias/"
	weight = 50

[[menu.main]]
	name   = "Ayuda"
	url    = "ayuda/"
	weight = 60

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
