name = "Golang Venezuela"
license = "MIT"
licenselink = "https://gitlab.com/golangve/sitioweb"
description = "Diseño web de la comunidad Golang en Venezuela"
homepage = "http://golang.org.ve"
tags = ["material design", "mdl", "comunidad", "google analytics", "responsive"]
features = []
min_version = 0.2

[author]
  name = "Junior Carrillo"
  homepage = "https://gitlab.com/juniorcarrillo"
