name = "Golang Venezuela"
license = "MIT"
licenselink = "https://gitlab.com/golangve/sitioweb"
description = "A material design theme for documentations."
homepage = "http://golang.org.ve"
tags = ["material", "documentation", "docs", "google analytics", "responsive"]
features = []
min_version = 0.20

[author]
  name = "Junior Carrillo"
  homepage = "https://gitlab.com/juniorcarrillo"

# If porting an existing theme
[original]
  name = "Martin Donath"
  homepage = "http://struct.cc/"
  repo = "https://github.com/squidfunk/mkdocs-material"
